//! Derived `Auth` values (stable index, expiry, auth kind, source kind) replayed against the values
//! the Go implementation computed for the same inputs (`fixtures/derived_cases.json`, generated by
//! `fixtures/gen/main.go`). The index must stay identical: usage stats and the management API key
//! credentials by it across restarts.

use std::collections::BTreeMap;
use std::path::Path;

use cpa_auth::Auth;
use serde::Deserialize;
use serde_json::{Map, Value};

#[derive(Deserialize)]
struct Case {
    name: String,
    provider: String,
    id: String,
    file_name: String,
    attributes: Option<BTreeMap<String, String>>,
    metadata: Option<Map<String, Value>>,
    index: String,
    expires_unix: Option<i64>,
    auth_kind: String,
    source_kind: String,
}

#[test]
fn index_expiry_and_kinds_match_go() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/derived_cases.json");
    let cases: Vec<Case> =
        serde_json::from_slice(&std::fs::read(path).expect("read cases")).expect("parse cases");
    assert!(cases.len() >= 15);

    for c in cases {
        let mut auth = Auth::new(c.id.clone(), c.provider.clone());
        auth.file_name = c.file_name.clone();
        auth.attributes = c.attributes.unwrap_or_default();
        auth.metadata = c.metadata.unwrap_or_default();

        assert_eq!(auth.ensure_index(), c.index, "{}: index", c.name);
        assert_eq!(
            auth.expiration_time().map(|t| t.timestamp()),
            c.expires_unix,
            "{}: expiry",
            c.name
        );
        assert_eq!(auth.auth_kind(), c.auth_kind, "{}: auth kind", c.name);
        assert_eq!(
            auth.auth_source_kind(),
            c.source_kind,
            "{}: source kind",
            c.name
        );
    }
}
