//! Differential test against the Go implementation: auth synthesis (ids, attributes, metadata,
//! indexes) and per-auth model registration for representative configs and auth files.
//!
//! Inputs: `fixtures/service_scenarios.json` (generated by `oracle/gen_scenarios.py`); expected
//! output: `fixtures/service_golden.json` (written by `oracle/zz_golden_test.go` running inside the
//! Go reference checkout).

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use chrono::Utc;
use cpa_auth::Auth;
use cpa_config::load_config;
use cpa_core::registry::{ModelInfo, ModelRegistry};
use cpa_runtime::service::synth::{StableIdGenerator, SynthesisContext, synthesize_auth_file, synthesize_config_auths};
use cpa_runtime::service::{
    claude_models_response, gemini_model_response, gemini_models_response, openai_models_response,
    register_models_for_auth,
};
use serde_json::{Map, Value, json};

const AUTH_DIR: &str = "/golden/auths";

fn fixture(name: &str) -> Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures").join(name);
    serde_json::from_slice(&std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))).unwrap()
}

/// `created` within a minute of now is the "NOW" marker both sides use for generated models.
fn created_value(created: i64) -> Value {
    if (created - Utc::now().timestamp()).abs() < 60 { json!("NOW") } else { json!(created) }
}

fn list(items: &[String]) -> Value {
    json!(items)
}

/// The same projection `zzModel` emits on the Go side.
fn model_dump(m: &ModelInfo) -> Value {
    let mut out = json!({
        "id": m.id,
        "metadata_model_id": m.metadata_model_id,
        "explicit_thinking": m.explicit_thinking,
        "explicit_input_modalities": m.explicit_input_modalities,
        "object": m.object,
        "created": created_value(m.created),
        "owned_by": m.owned_by,
        "type": m.r#type,
        "display_name": m.display_name,
        "name": m.name,
        "version": m.version,
        "description": m.description,
        "input_token_limit": m.input_token_limit,
        "output_token_limit": m.output_token_limit,
        "supported_generation_methods": list(&m.supported_generation_methods),
        "context_length": m.context_length,
        "max_context_length": m.max_context_length,
        "max_completion_tokens": m.max_completion_tokens,
        "supported_parameters": list(&m.supported_parameters),
        "supported_input_modalities": list(&m.supported_input_modalities),
        "supported_output_modalities": list(&m.supported_output_modalities),
        "supports_web_search": m.supports_web_search,
        "support_configuration_update": m.support_configuration_update,
        "thinking": serde_json::to_value(&m.thinking).unwrap(),
        "user_defined": m.user_defined,
        "is_compat": m.is_compat,
    });
    if let Some(ws) = m.native_capabilities.as_ref().and_then(|c| c.web_search) {
        out["native_web_search"] = json!(ws);
    }
    out
}

/// Go marshals nil slices as `null`; treat them like empty ones.
fn null_to_empty_lists(v: &mut Value) {
    if let Value::Object(map) = v {
        for key in [
            "supported_generation_methods",
            "supported_parameters",
            "supported_input_modalities",
            "supported_output_modalities",
        ] {
            if map.get(key).is_some_and(Value::is_null) {
                map.insert(key.into(), json!([]));
            }
        }
    }
}

fn auth_dump(a: &mut Auth) -> Value {
    let index = a.ensure_index();
    let metadata = Value::Object(a.metadata.clone());
    json!({
        "id": a.id,
        "provider": a.provider,
        "label": a.label,
        "prefix": a.prefix,
        "status": serde_json::to_value(a.status).unwrap(),
        "disabled": a.disabled,
        "proxy_url": a.proxy_url,
        "file_name": a.file_name,
        "attributes": a.attributes,
        "metadata": metadata,
        "index": index,
        "auth_kind": a.auth_kind(),
        "source_kind": a.auth_source_kind(),
    })
}

/// First differing keys of two JSON objects, for readable failures.
fn diff_fields(path: &str, want: &Value, got: &Value, out: &mut Vec<String>) {
    match (want, got) {
        (Value::Object(w), Value::Object(g)) => {
            let keys: BTreeSet<&String> = w.keys().chain(g.keys()).collect();
            for key in keys {
                let (w, g) = (w.get(key).unwrap_or(&Value::Null), g.get(key).unwrap_or(&Value::Null));
                diff_fields(&format!("{path}.{key}"), w, g, out);
            }
        }
        _ if want != got => out.push(format!("{path}: go={want} rust={got}")),
        _ => {}
    }
}

#[test]
fn id_generator_matches_go() {
    let golden = fixture("service_golden.json");
    let mut gen_ = StableIdGenerator::new();
    let got: Vec<Value> = [vec!["a", "b"], vec!["a", "b"], vec![" a ", "b"], vec!["a", "b", "c"], vec!["a", "b"]]
        .iter()
        .map(|parts| {
            let (id, token) = gen_.next("k", parts);
            json!([id, token])
        })
        .collect();
    assert_eq!(golden["id_gen"], Value::Array(got));
}

#[test]
fn synthesis_and_model_registration_match_go() {
    let scenarios = fixture("service_scenarios.json");
    let golden = fixture("service_golden.json");
    let golden_scenarios = golden["scenarios"].as_array().unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let mut problems: Vec<String> = Vec::new();

    for (sc, gold) in scenarios.as_array().unwrap().iter().zip(golden_scenarios) {
        let name = sc["name"].as_str().unwrap();
        assert_eq!(gold["name"], sc["name"]);
        let cfg_path = tmp.path().join(format!("{name}.yaml"));
        std::fs::write(&cfg_path, sc["config_yaml"].as_str().unwrap()).unwrap();
        let mut cfg = load_config(&cfg_path).unwrap_or_else(|e| panic!("{name}: {e}"));
        cfg.auth_dir = AUTH_DIR.into();
        let ctx = SynthesisContext { config: &cfg, auth_dir: AUTH_DIR, now: Utc::now() };

        let mut auths = synthesize_config_auths(&ctx).unwrap();
        let files: BTreeMap<String, String> = sc
            .get("auth_files")
            .and_then(Value::as_object)
            .map(|m| m.iter().map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string())).collect())
            .unwrap_or_default();
        let mut file_errors = BTreeSet::new();
        for (file, content) in &files {
            if !file.to_lowercase().ends_with(".json") || content.is_empty() {
                continue;
            }
            match synthesize_auth_file(&ctx, &format!("{AUTH_DIR}/{file}"), content.as_bytes()) {
                Ok(Some(auth)) => auths.push(auth),
                Ok(None) => {}
                Err(_) => {
                    file_errors.insert(file.clone());
                }
            }
        }
        let want_errors: BTreeSet<String> = gold["file_errors"].as_object().unwrap().keys().cloned().collect();
        if want_errors != file_errors {
            problems.push(format!("{name}: file errors go={want_errors:?} rust={file_errors:?}"));
        }

        let registry = ModelRegistry::default();
        for auth in &auths {
            register_models_for_auth(&registry, &cfg, auth);
        }
        let want_auths = gold["auths"].as_array().unwrap();
        if want_auths.len() != auths.len() {
            let ids: Vec<&str> = auths.iter().map(|a| a.id.as_str()).collect();
            problems.push(format!("{name}: auth count go={} rust={} ({ids:?})", want_auths.len(), auths.len()));
            continue;
        }
        let mut provider_ids = BTreeSet::new();
        for (want, auth) in want_auths.iter().zip(auths.iter_mut()) {
            let got = auth_dump(auth);
            let mut want_fields = want.clone();
            let want_models = want_fields.as_object_mut().unwrap().remove("models").unwrap();
            // Go leaves nil metadata as null for config auths without overrides.
            if want_fields["metadata"].is_null() {
                want_fields["metadata"] = json!({});
            }
            let mut diffs = Vec::new();
            diff_fields(&format!("{name}/{}", auth.id), &want_fields, &got, &mut diffs);
            problems.extend(diffs);

            let models = registry.get_models_for_client(&auth.id);
            let want_models = want_models.as_array().unwrap();
            let want_ids: Vec<String> = want_models
                .iter()
                .map(|m| m.as_str().map(str::to_string).unwrap_or_else(|| m["id"].as_str().unwrap().to_string()))
                .collect();
            let got_ids: Vec<String> = models.iter().map(|m| m.id.clone()).collect();
            if want_ids != got_ids {
                problems.push(format!("{name}/{}: model ids go={want_ids:?} rust={got_ids:?}", auth.id));
                continue;
            }
            for (want, got) in want_models.iter().zip(&models) {
                provider_ids.insert(got.id.clone());
                if want.is_object() {
                    let mut got = model_dump(got);
                    let mut want = want.clone();
                    null_to_empty_lists(&mut want);
                    null_to_empty_lists(&mut got);
                    diff_fields(&format!("{name}/{}/{}", auth.id, got["id"]), &want, &got, &mut problems);
                }
            }
        }

        for id in &provider_ids {
            let want: BTreeSet<String> = gold["providers"][id].as_array().unwrap().iter().map(|p| p.as_str().unwrap().to_string()).collect();
            let got: BTreeSet<String> = registry.get_model_providers(id).into_iter().collect();
            if want != got {
                problems.push(format!("{name}: providers of {id} go={want:?} rust={got:?}"));
            }
        }
        for handler in ["openai", "claude", "gemini"] {
            let want: BTreeSet<String> = gold["lists"][handler].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
            let got: BTreeSet<String> = registry
                .get_available_models(handler)
                .iter()
                .filter_map(|m: &Map<String, Value>| m.get("id").or_else(|| m.get("name")).and_then(Value::as_str).map(str::to_string))
                .collect();
            if want != got {
                let only_go: Vec<_> = want.difference(&got).collect();
                let only_rust: Vec<_> = got.difference(&want).collect();
                problems.push(format!("{name}: {handler} list only-go={only_go:?} only-rust={only_rust:?}"));
            }
        }

        // The real handlers' response bodies (key order included): re-serializing the Go body
        // through `Value` keeps its key order, so string equality checks order too.
        if let Some(handlers) = gold["handlers"].as_object() {
            let canon = |raw: &Value| serde_json::to_string(&serde_json::from_str::<Value>(raw["body"].as_str().unwrap()).unwrap()).unwrap();
            let mut check = |what: &str, want: String, got: String| {
                if want != got {
                    problems.push(format!("{name}: {what} body differs\n  go  ={want:.300}\n  rust={got:.300}"));
                }
            };
            // Go builds the openai and gemini lists in map-iteration order; ours is sorted by id.
            let unordered = |mut v: Value, key: &str| {
                v[key].as_array_mut().unwrap().sort_by_key(Value::to_string);
                v.to_string()
            };
            let parsed = |raw: &Value| serde_json::from_str::<Value>(raw["body"].as_str().unwrap()).unwrap();
            check("openai", unordered(parsed(&handlers["openai"]), "data"), unordered(openai_models_response(&registry), "data"));
            check("claude", canon(&handlers["claude"]), claude_models_response(&registry, false).to_string());
            check("gemini", unordered(parsed(&handlers["gemini"]), "models"), unordered(gemini_models_response(&registry), "models"));
            let hit = gold["handlers"]["gemini_name"].as_str().unwrap();
            // Registry names are bare, so Go answers 404 for the `models/`-prefixed form.
            for (what, key, action) in [
                ("gemini get prefixed", "gemini_get_prefixed", hit.to_string()),
                ("gemini get bare", "gemini_get_bare", hit.trim_start_matches("models/").to_string()),
            ] {
                let got = gemini_model_response(&registry, &format!("/{action}"));
                if handlers[key]["status"] == 200 {
                    check(what, canon(&handlers[key]), got.expect("gemini model hit").to_string());
                } else if got.is_some() {
                    check(what, "404".into(), "found".into());
                }
            }
            assert_eq!(handlers["gemini_get_missing"]["status"], 404);
            assert!(gemini_model_response(&registry, "/models/no-such-model").is_none());
        }
    }
    assert!(problems.is_empty(), "{} differences vs Go:\n{}", problems.len(), problems.iter().take(60).cloned().collect::<Vec<_>>().join("\n"));
}
