//! Every payload type must decode what Go's `encoding/json` produced (fields filled by reflection,
//! plus the all-zero value) and encode back to the same JSON value. The fixture is generated by a
//! Go program that marshals each `sdk/pluginapi` struct.

use cpa_pluginapi::api::*;
use serde::Serialize;
use serde::de::DeserializeOwned;
use serde_json::Value;

fn fixture() -> serde_json::Map<String, Value> {
    let raw = include_str!("data/go_shapes.json");
    match serde_json::from_str::<Value>(raw) {
        Ok(Value::Object(m)) => m,
        _ => panic!("fixture is not an object"),
    }
}

/// Go route structs carry a `Handler` interface that is always null on the wire and has no Rust
/// counterpart.
fn strip_handler(v: &mut Value) {
    match v {
        Value::Object(m) => {
            m.shift_remove("Handler");
            m.values_mut().for_each(strip_handler);
        }
        Value::Array(a) => a.iter_mut().for_each(strip_handler),
        _ => {}
    }
}

fn check<T: Serialize + DeserializeOwned>(fx: &serde_json::Map<String, Value>, name: &str, failures: &mut Vec<String>) {
    for mode in ["full", "zero"] {
        let key = format!("{name}/{mode}");
        let Some(go) = fx.get(&key) else {
            failures.push(format!("{key}: missing from fixture"));
            continue;
        };
        let mut go = go.clone();
        strip_handler(&mut go);
        let go = &go;
        let parsed: T = match serde_json::from_value(go.clone()) {
            Ok(v) => v,
            Err(e) => {
                failures.push(format!("{key}: decode failed: {e}"));
                continue;
            }
        };
        let back = serde_json::to_value(&parsed).unwrap_or(Value::Null);
        if &back != go {
            failures.push(format!("{key}:\n  go   {go}\n  rust {back}"));
        }
    }
}

macro_rules! shapes {
    ($($ty:ident = $name:literal),* $(,)?) => {
        #[test]
        fn rust_types_match_go_json() {
            let fx = fixture();
            let mut failures = Vec::new();
            $( check::<$ty>(&fx, $name, &mut failures); )*
            assert!(failures.is_empty(), "{} mismatches:\n{}", failures.len(), failures.join("\n"));
        }
    };
}

shapes! {
    PluginMetadata = "Metadata", ConfigField = "ConfigField", ModelInfo = "ModelInfo",
    HostConfigSummary = "HostConfigSummary", AuthData = "AuthData",
    AuthParseRequest = "AuthParseRequest", AuthParseResponse = "AuthParseResponse",
    AuthLoginStartRequest = "AuthLoginStartRequest", AuthLoginStartResponse = "AuthLoginStartResponse",
    AuthLoginPollRequest = "AuthLoginPollRequest", AuthLoginPollResponse = "AuthLoginPollResponse",
    AuthRefreshRequest = "AuthRefreshRequest", AuthRefreshResponse = "AuthRefreshResponse",
    ModelRegistrationRequest = "ModelRegistrationRequest", ModelRegistrationResponse = "ModelRegistrationResponse",
    StaticModelRequest = "StaticModelRequest", AuthModelRequest = "AuthModelRequest", ModelResponse = "ModelResponse",
    FrontendAuthRequest = "FrontendAuthRequest", FrontendAuthResponse = "FrontendAuthResponse",
    SchedulerPickRequest = "SchedulerPickRequest", SchedulerPickResponse = "SchedulerPickResponse",
    ModelRouteRequest = "ModelRouteRequest", ModelRouteResponse = "ModelRouteResponse",
    HostModelExecutionRequest = "HostModelExecutionRequest", HostModelExecutionResponse = "HostModelExecutionResponse",
    HostModelStreamResponse = "HostModelStreamResponse", HostModelStreamReadRequest = "HostModelStreamReadRequest",
    HostModelStreamReadResponse = "HostModelStreamReadResponse", HostModelStreamCloseRequest = "HostModelStreamCloseRequest",
    HostAuthFileEntry = "HostAuthFileEntry", HostAuthGetRequest = "HostAuthGetRequest",
    HostAuthGetResponse = "HostAuthGetResponse", HostAuthGetRuntimeResponse = "HostAuthGetRuntimeResponse",
    HostAuthSaveRequest = "HostAuthSaveRequest", HostAuthSaveResponse = "HostAuthSaveResponse",
    HostAffinityLookupRequest = "HostAffinityLookupRequest", HostAffinityLookupResponse = "HostAffinityLookupResponse",
    HttpWireProfile = "HTTPWireProfile", HttpRequest = "HTTPRequest", HttpResponse = "HTTPResponse",
    ExecutorHttpRequest = "ExecutorHTTPRequest", ExecutorHttpResponse = "ExecutorHTTPResponse",
    ExecutorRequest = "ExecutorRequest", ExecutorResponse = "ExecutorResponse",
    ExecutorStreamChunk = "ExecutorStreamChunk",
    RequestTransformRequest = "RequestTransformRequest", ResponseTransformRequest = "ResponseTransformRequest",
    RequestInterceptRequest = "RequestInterceptRequest", RequestInterceptResponse = "RequestInterceptResponse",
    RequestCompletion = "RequestCompletion", ResponseInterceptRequest = "ResponseInterceptRequest",
    ResponseInterceptResponse = "ResponseInterceptResponse", StreamChunkInterceptRequest = "StreamChunkInterceptRequest",
    StreamChunkInterceptResponse = "StreamChunkInterceptResponse", WebSocketResponseEvent = "WebSocketResponseEvent",
    PayloadResponse = "PayloadResponse", ThinkingApplyRequest = "ThinkingApplyRequest",
    UsageRecord = "UsageRecord", CommandLineRegistrationRequest = "CommandLineRegistrationRequest",
    CommandLineRegistrationResponse = "CommandLineRegistrationResponse", CommandLineExecutionRequest = "CommandLineExecutionRequest",
    CommandLineExecutionResponse = "CommandLineExecutionResponse", ManagementRegistrationRequest = "ManagementRegistrationRequest",
    ManagementRoute = "ManagementRoute", ResourceRoute = "ResourceRoute",
    ManagementRegistrationResponse = "ManagementRegistrationResponse", ManagementRequest = "ManagementRequest",
    ManagementResponse = "ManagementResponse", QuotaDescribeRequest = "QuotaDescribeRequest",
    QuotaDescribeResponse = "QuotaDescribeResponse", QuotaFetchRequest = "QuotaFetchRequest",
    QuotaFetchResponse = "QuotaFetchResponse", QuotaResetRequest = "QuotaResetRequest",
    QuotaResetResponse = "QuotaResetResponse",
}
