[package]
name = "cpa-json"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = { workspace = true, features = ["unbounded_depth"] }
serde = "1"
serde_stacker = "0.1"
memchr = "2"
simdutf8 = "0.1"

[dev-dependencies]
indexmap.workspace = true
perf-event2 = "0.7"
